forums/urls.py
from django.urls import path
from forums import views


urlpatterns = [
    #path("forum", views.forum.as_view(), name='forum'),
    path("all_orders", views.all_orders.as_view(), name='all_orders'),
    path("review/<int:pk>", views.review.as_view(), name='review')
]

home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('defaultHome', defaultHome, name='defaultHome'),
    path('logOut', logOut, name='logoutNav'),
    path('loginNav', loginNav, name='loginNav'),
    path('registerNav', registerNav, name='regNav'),
    path('ordersNav', ordersNav, name='ordersNav'),
    path('menuNav', menuNav, name='menuNav'),
    path('forumNav', forumNav, name='forumNav'),
    path('dashNav', dashNav, name='dashNav')
]

pipin_hot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='home/defaultHome')),
    path('admin/', admin.site.urls),
    path('reg_log/', include("reg_log.urls")),
    path('forums/', include("forums.urls")),
    path('order_system/', include("order_system.urls")),
    path('menu/', include("menu.urls")),
    path('home/', include('home.urls')),
    path('delivery/', include("delivery.urls")),
    path('dashboard/', include("dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forums/models.py
from tkinter import CASCADE
from django.db import models
from numpy import True_
from reg_log.models import User
from order_system.models import OrderModel

# Create your models here.


class Forum_Posts(models.Model):
    post_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    article_content = models.CharField(default=0, max_length=100)
    subject = models.CharField(max_length=50)
    rating = models.IntegerField(default=10)


class Review(models.Model):
    complainee = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    reviewed_by_manager = models.BooleanField(default=False)
    order_assigned = models.ForeignKey(
        OrderModel, on_delete=models.CASCADE, blank=True, null=True)


class EmployeeReview(models.Model):
    review_order = models.ForeignKey(
        Review, on_delete=models.CASCADE, blank=True)
    is_complaint = models.BooleanField(default=False, blank=True)
    employee_name = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    description = models.CharField(max_length=100, blank=True)
    # ADD ITEM ASSOCIATED

forums/forms.py
from dataclasses import fields
from django.forms import ModelForm
from django import forms
from models import Forum_Posts, Review


class PostForm(ModelForm):
    class Meta:
        model = Forum_Posts
        fields = ['post_user', 'article_content',
                  'subject', 'rating', 'reviewed_by_manager']


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['user', 'rating', 'is_complaint',
                  'subject', 'reviewd_by_manager']

forums/views.py
from operator import is_
from django.shortcuts import redirect, render
from django.views import generic
from forums.models import Forum_Posts
from menu.models import FoodItem
from order_system.models import OrderModel
from django.views import View
from forums.models import Review, EmployeeReview
from reg_log.models import User

# Create your views here.

# @login_Required


class all_orders(generic.ListView):
    def get(self, request, *args, **kwargs):
        # get every item from each category

        template_name = 'forum.html'
        if request.user.is_authenticated:
            username = request.user.username
            orders = OrderModel.objects.filter(
                name__startswith=username)

        # pass into context

        context = {
            'Orders': orders

        }
        # render template
        return render(request, 'all_orders.html', context)

    def post(self, request, *args, **kwarg):

        user = User.objects.get(pk=request.user.pk)
        order_pk = request.POST.get('order')
        review = Review.objects.create(
            complainee=user, reviewed_by_manager=False, order_assigned=OrderModel.objects.get(pk=order_pk))

        return redirect("review", pk=review.pk)


class review(View):

    def get(self, request, pk, *args, **kwargs):

        review = Review.objects.get(pk=pk)
        order = OrderModel.objects.get(pk=review.order_assigned.pk)
        is_delivery = order.is_delivery

        context = {
            'review': review,
            'order': order,
            'is_delivery': is_delivery

        }

        return render(request, "review.html", context)

    def post(self, request, pk, *args, **kwargs):

        user = User.objects.get(pk=request.user.pk)
        review = Review.objects.get(pk=pk)
        items = request.POST.getlist('items[]')

        if (review.order_assigned.is_delivery):

            description = request.POST.get("description")
            is_complaint = False
            selection = request.POST.get('review delivery')
            if "complain" == selection:
                is_complaint = True

            else:
                is_complaint = False

            delivery_review = EmployeeReview.objects.create(review_order=review,
                                                            is_complaint=is_complaint, employee_name=None, description=description)
            for item in items:
                menu_item = FoodItem.objects.get(pk=int(item))
                rating = request.POST.get(menu_item.name)
                menu_item.rating = menu_item.rating + int(rating)
                menu_item.quantity_ordered = menu_item.quantity_ordered + 1
                menu_item.save()

        else:
            for item in items:
                menu_item = FoodItem.objects.get(pk=int(item))

                selection = request.POST.get(
                    menu_item.chef_name.username+','+menu_item.name)
                description = request.POST.get(
                    "description," + str(menu_item.pk))

                # {{item.chef_name.username}},{{item.name}}
                if "complain" == selection:
                    is_complaint = True
                else:
                    is_complaint = False

                EmployeeReview.objects.create(review_order=review,
                                              is_complaint=is_complaint, employee_name=menu_item.chef_name, description=description)

                rating = request.POST.get(menu_item.name)
                menu_item.rating = menu_item.rating + int(rating)
                menu_item.quantity_ordered = menu_item.quantity_ordered + 1
                menu_item.save()
        # review_employee = Complaint.objects.create(
        #     complainee=request.user, description=description, is_delivery=is_delivery)

        return redirect("all_orders")


# class review_confirmation

# class deliverer_register(CreateView):
#     model = User
#     form_class = DelivererSignUpForm
#     template_name = '../templates/deliverer_register.html'

forums/templates/all_orders.html
{%load static %}

<!DOCTYPE html>

<head>

</head>
<body>
    
    {% for order in Orders %}

    <p>Customer name: {{order.name}}</p>


    {% for item in order.items.all %}

    {{item.name}},
   
    {% endfor %} 
    <form method="POST"> 
        {% csrf_token %}
        <input type="checkbox" name="order" value="{{ order.pk }}">
        
            <button>Review This One!</button>
        
    </form> 
    
    <br>

    {%endfor%}

</body>

forums/templates/forum.html
<!DOCTYPE html>

<head>

</head>
<body>
    
    {% for forum in forum_posts_list %}

    {{forum.post_user}}

    {%endfor%}

</body>

forums/templates/review.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Review Order</title>
    <link rel = "stylesheet" href = "{% static '/css/usrDashboard.css' %}">
    <link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<style>
    h1 {
        margin-top: 2.5vw;
        font-size: 2.5vw;
        font-family: "Garamond", serif;
        text-align: center;
        font-weight: bold;
    }

    hr.solid {
        border-top: 1px solid rgb(109, 100, 100);
        width: 100%;
        height: 1px;
    }
    
    a {
        margin-left: 30px;
        font-size: 2vw;
        text-align: center;
    }

</style>
<body>
    <a href = "{% url 'defaultHome' %}"> <img src="{% static 'Pipin-Hot.png' %}"/> </a>

    
    {{review.order.name.all}}
    <br>
    <form method="POST">
        {% csrf_token %}
        
        {% if is_delivery %}
        {% for item in review.order_assigned.items.all %}

        <div>
           
            <u1 style = "list-style: none;">
                {{item.name}}
                <li style = "padding: 20px; margin-top: 0.2vw; margin-bottom: 0.70vw"> 
                    <img style = "width:0.8vw; height:0.75vw;" src = "{{ item.img.url }}"/>

                    <label for="{{item.name}}">Review this Item</label>
                    <input type="hidden" name="items[]" value="{{ item.pk }}">
                    <input type="number" min= "0" max="10" name="{{ item.name}}" placeholder="Rate!">  
                </li>
              
            </u1>

        </div>
    
    
        {% endfor %} 
            <select id="delivery_rating" name="review delivery">

                <option value = "complain">Complain</option>
                <option value = "compliment">Compliment</option>
            </select>      
            <input type="text" placeholder="Rate delivery" name="description"/>
        </div>
            {% else %}
            {% for item in review.order_assigned.items.all %}

    
                    
                    <li style = "padding: 20px; margin-top: 0.2vw; margin-bottom: 0.70vw"> 
                        {{item.name}}
                        <img style = "width:0.8vw; height:0.75vw;" src = "{{ item.img.url }}"/>
                        <br>
    
                    <label for="{{item.name}}">Review this Item</label>
                    <input type="hidden" name="items[]" value="{{ item.pk }}">
                    <input type="number" min= "0" max="10" name="{{ item.name}}" placeholder="Rate!">
                    <select id="chef_rating" name="{{item.chef_name.username}},{{item.name}}">

                        <option value = "complain">Complain</option>
                        <option value = "compliment">Compliment</option>
                    </select>      
                    <input type="text" placeholder="Rate Chef" name="description,{{item.pk}}"/>
                    </li>


                <div>
                    
                </div>
        
            {% endfor %} 
                    
        </div>

            {% endif %}
        <input type="text" placeholder="What did you think" name="description"/>
        <button>Submit</button>
    </form>


</body>