home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('defaultHome', defaultHome, name='defaultHome'),
    path('logOut', logOut, name='logoutNav'),
    path('loginNav', loginNav, name='loginNav'),
    path('registerNav', registerNav, name='regNav'),
    path('ordersNav', ordersNav, name='ordersNav'),
    path('menuNav', menuNav, name='menuNav'),
    path('forumNav', forumNav, name='forumNav'),
    path('dashNav', dashNav, name='dashNav')
]

pipin_hot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='home/defaultHome')),
    path('admin/', admin.site.urls),
    path('reg_log/', include("reg_log.urls")),
    path('forums/', include("forums.urls")),
    path('order_system/', include("order_system.urls")),
    path('menu/', include("menu.urls")),
    path('home/', include('home.urls')),
    path('delivery/', include("delivery.urls")),
    path('dashboard/', include("dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reg_log/urls.py
from django.urls import path
from reg_log import views

urlpatterns = [
     path("index", views.index, name='index'),
     path("register", views.register, name='register'),
     path('customer_register', views.customer_register.as_view(),
         name='customer_register'),
     path('chef_register', views.chef_register.as_view(),
         name='chef_register'),
     path('deliverer_register', views.deliverer_register.as_view(),
         name='deliverer_register'),
     path('sales_register', views.sales_register.as_view(),
          name='sales_register'),
     path('manager_register', views.manager_register.as_view(),
          name='manager_register'),
     path("login", views.login_view, name='login'),
     path("logout", views.logout_view, name="logout")
]

reg_log/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

# class Task(models.Model):
#   class Meta:
#       permission = [
#           ("change_tast_status", "Can do something"),
#           ("close_task", "something else")
#           ]
#
#

class User(AbstractUser):
    user_choices = [
    ('customer', 'Customer'),
    ('chef', 'Chef'),
    ('delivery', 'Delivery'),
    ('manager', 'Manager'),
    ('sales', 'Sales Associate')
    ]

    is_customer = models.BooleanField(default=False)
    is_chef = models.BooleanField(default=False)
    is_deliverer = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    is_sales = models.BooleanField(default=False)
    username = models.CharField(max_length=50, unique=True)
    user_type = models.CharField(max_length=30, choices=user_choices, blank=True)


class Customer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    address = models.CharField(max_length=60)
    account_funds = models.IntegerField(default=0)
    warnings = models.IntegerField(default=0)
    is_vip = models.BooleanField(default=False)
    # top_three = models.OneToOneField(
    #     TopThree, on_delete=models.CASCADE, blank=True)


class Chef(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=30)
    salary = models.BigIntegerField(default=0)
    rating = models.IntegerField(default=0)


class Deliverer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=30)
    salary = models.BigIntegerField(default=0)


class Manager(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    salary = models.BigIntegerField(default=0)


class SalesAssociate(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    salary = models.BigIntegerField(default=0)

reg_log/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.db import IntegrityError, transaction
from .models import Customer, Chef, Manager, Deliverer, SalesAssociate, User
from django import forms
from django.core.exceptions import ValidationError

BIGINT_MIN = -9223372036854775808
BIGINT_MAX = 9223372036854775807

class UserTypeForm(forms.Form):
    user_choices = [
    ('customer', 'Customer'),
    ('chef', 'Chef'),
    ('delivery', 'Delivery'),
    ('manager', 'Manager'),
    ('sales', 'Sales Associate')
    ]
    user_type = forms.ChoiceField(required=True, label=('Register as:'), choices=user_choices)


class CustSignUpForm(UserCreationForm):
    email = forms.CharField(required=True)
    first_name = forms.CharField(required=True, max_length=30)
    last_name = forms.CharField(required=True, max_length=30)
    address = forms.CharField(required=True, max_length=60)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.username = self.cleaned_data.get('username')
        user.save()
        customer = Customer.objects.create(user=user)
        customer.first_name = self.cleaned_data.get('first_name')
        customer.last_name = self.cleaned_data.get('last_name')
        customer.address = self.cleaned_data.get('address')
        customer.account_funds = 0
        customer.save()

        return user


class ChefSignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=30)
    #salary = forms.IntegerField(required=True, min_value=BIGINT_MIN, max_value=BIGINT_MAX)
    #rating = forms.IntegerField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_chef = True
        user.username = self.cleaned_data.get('username')
        user.save()
        chef = Chef.objects.create(user=user)
        chef.first_name = self.cleaned_data.get('first_name')
       #chef.salary = self.cleaned_data.get('salary')
       #chef.rating = self.cleaned_data('salary')
        chef.save()

        return user


class DelivererSignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=30)
    salary = forms.IntegerField(required=True, min_value=BIGINT_MIN, max_value=BIGINT_MAX)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_deliverer = True
        user.username = self.cleaned_data.get('username')
        user.save()
        deliverer = Deliverer.objects.create(user=user)
        deliverer.first_name = self.cleaned_data.get('first_name')
        deliverer.salary = self.cleaned_data.get('salary')
        deliverer.save()

        return user


class SalesAssociateSignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=30)
    last_name = forms.CharField(required=True, max_length=30)
    salary = forms.IntegerField(required=True, min_value=BIGINT_MIN, max_value=BIGINT_MAX)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_sales = True
        user.username = self.cleaned_data.get('username')
        user.save()
        sales = SalesAssociate.objects.create(user=user)
        sales.first_name = self.cleaned_data.get('first_name')
        sales.last_name = self.cleaned_data.get('last_name')
        sales.salary = self.cleaned_data.get('salary')
        sales.save()


class ManagerSignUpForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=30)
    last_name = forms.CharField(required=True, max_length=30)
    salary = forms.IntegerField(required=True, min_value=BIGINT_MIN, max_value=BIGINT_MAX)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_manager = True
        user.username = self.cleaned_data.get('username')
        user.save()
        manager = Manager.objects.create(user=user)
        manager.first_name = self.cleaned_data.get('first_name')
        manager.last_name = self.cleaned_data.get('last_name')
        manager.salary = self.cleaned_data.get('salary')
        manager.save()

reg_log/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from .models import User, Customer, Chef, Deliverer
from .forms import CustSignUpForm, ChefSignUpForm, DelivererSignUpForm, ManagerSignUpForm, SalesAssociateSignUpForm, UserTypeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def index(request, context={}):
    return render(request, 'defaultHome.html')


@csrf_exempt
def register(request, context={}):
    if (request.user.is_authenticated):
        return redirect('defaultHome.html')

    if(request.method == 'POST'):
        utform = UserTypeForm(request.POST)
        delivform = DelivererSignUpForm()
        custform = CustSignUpForm()
        chefform = ChefSignUpForm()
        salesform = SalesAssociateSignUpForm()
        managerform = ManagerSignUpForm()
        context = {'ut' : ''}
        if(utform.is_valid()):
            ut = utform.cleaned_data['user_type']
            context['ut'] = ut

            if(ut == 'delivery'):
                form = DelivererSignUpForm(request.POST)
                print('hello')
            elif(ut == 'customer'):
                form = CustSignUpForm(request.POST)
            elif(ut == 'chef'):
                form = ChefSignUpForm(request.POST)
            elif(ut == 'manager'):
                form = ManagerSignUpForm(request.POST)
            else:
                form = SalesAssociateSignUpForm(request.POST)

            if (form.is_valid()):
                form.instance.is_active = False
                form.save()
                return redirect('login')
            else:
                context['form'] = form
            

    else:
        utform = UserTypeForm()
        # chefform = ChefSignUpForm()
        # salesform = SalesAssociateSignUpForm()

    context['utform'] = utform
    # context['form'] = DelivererSignUpForm()
    # context['custform'] = custform
    # context['chefform'] = chefform
    # context['salesform'] = salesform
    # context['managerform'] = managerform

    return render(request, 'register.html', context)


class customer_register(CreateView):
    model = User
    form_class = CustSignUpForm
    template_name = '../templates/customer_register.html'
    def get_success_url(self) -> str:
        return super().get_success_url()



class chef_register(CreateView):
    model = User
    form_class = ChefSignUpForm
    template_name = 'chef_register.html'
    def get_success_url(self) -> str:
        return super().get_success_url()



class deliverer_register(CreateView):
    model = User
    form_class = DelivererSignUpForm
    template_name = '../templates/deliverer_register.html'
    def get_success_url(self) -> str:
        return super().get_success_url()


class sales_register(CreateView):
    model = User
    form_class = SalesAssociateSignUpForm
    template_name = 'sales_register.html'

class manager_register(CreateView):
    model = User
    form_class = ManagerSignUpForm
    template_name = 'manager_register.html'


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request,'defaultHome.html')
            else:
                messages.error(request, "Incorrect username and/or password")
        else:
            messages.error(request, "Form not valid")

    # context is
    if (request.user.is_authenticated):
        if(Deliverer.objects.filter(pk=request.user).exists()):
            return redirect('deliveryui')

    return render(request, '../templates/login.html', context={'form': AuthenticationForm()})


def logout_view(request):
    logout(request)
    return render(request,'defaultHome.html')

reg_log/templates/chef_register.html
    <div class="sub-form-container">
        <form action="{% url 'defaultHome' %}" method="POST" novalidate>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
    </div>

reg_log/templates/customer_register.html
    <div class="sub-form-container">
        <form action="{% url 'customer_register' %}" method="POST" novalidate>
            {% csrf_token %}
            {{form.as_p}}
        <input type="submit" value="Submit">
    
    </div>

reg_log/templates/deliverer_register.html
    <div class="sub-form-container">
        <form action="{% url 'register' %}" method="POST" novalidate>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
    </div>

reg_log/templates/index.html
<!DOCTYPE html>

<head>

</head>
<body>
    <p1> 
        hi what
    </p1> 
    {% for forum in forum_posts_list %}

    {{forum.post_user}}
    {{forum.post_user.is_customer}}
    {{forum.article_content}},
    {{forum.subject}},
    rating:{{forum.rating}}

    {%endfor%}
    


</body>






<!-- <!DOCTYPE html>


<head>

</head>

<body>
    Index page dis one right
</body> -->

reg_log/templates/login.html
{% extends 'defaultHome.html' %}

{% block css %}
<style>
.grid-container {
    position: absolute;
    display: grid;
    margin: 12.5vw;
    width: 75vw;
    justify-content: space-evenly;

    grid-template-columns: 1fr 1fr 1fr;
    grid-auto-rows: minmax(100px, auto);
    column-gap: 1vw;
}
.grid-item {
    display: flex;
    background-color: darkgrey;
    justify-content: center;
}
</style>
{% endblock %}


{% block content %}
    <div class="grid-container">
            <form action="{% url 'login' %}" method = "POST" nonvalidate>
                {% csrf_token %}
                {{form}}
                <input type="submit" value="Submit">
            </form>
    </div>       
{% endblock %}

reg_log/templates/manager_register.html
<div class="sub-form-container">
    <form action="{% url 'manager_register' %}" method="POST" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
</div>

reg_log/templates/register.html
{% extends 'defaultHome.html' %}

{% block css %}
<style>
    .grid-container {
        position: absolute;
        display: grid;
        margin: 12.5vw;
        width: 75vw;
        justify-content: space-evenly;

        grid-template-columns: 1fr 1fr 1fr;
        grid-auto-rows: minmax(100px, auto);
        column-gap: 1vw;
    }

    .grid-item {
        display: flex;
        background-color: darkgrey;
        justify-content: center;
    }

    .form-container {
        display: flex;
        position: absolute;
        top: 100.5px;
        margin-top: 10px;
    }

    .sub-form-container {
        display: flex;
        position: absolute;
        top: 200px;
        margin-top: 10px;
    }
</style>
{% endblock %}


{% block content %}
<div class="form-container">
    <form method="POST" action="{% url 'register' %}">
        {% csrf_token %}
        <select id="user_type_select" name="user_type">
            <option value="customer" selected>Customer</option>
            <option value="chef">Chef</option>
            <option value="manager">Manager</option>
            <option value="sales">Sales Associate</option>
            <option value="delivery">Delivery</option>
        </select>
        <input type="hidden" name="csrfmiddlewaretoken"
            value="JlTCp1bmAkAxdvBkf6XaPNUXzgDxqKjAzQkutRhopyIXkYNwOEzYptS7TsCiJMCX">
        <ul class="errorlist">
            <li>This field is required.</li>
        </ul>
        <p>
            <label for="id_username">Username:</label>
            <input type="text" name="username" maxlength="50" autocapitalize="none" autocomplete="username" autofocus
                required id="id_username">
        </p>
        <ul class="errorlist">
            <li>This field is required.</li>
        </ul>
        <p>
            <label for="id_password1">Password:</label>
            <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
            <span class="helptext">
                <ul>
                    <li>Your password can’t be too similar to your other personal information.</li>
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can’t be a commonly used password.</li>
                    <li>Your password can’t be entirely numeric.</li>
                </ul>
            </span>
        </p>
        <ul class="errorlist">
            <li>This field is required.</li>
        </ul>
        <p>
            <label for="id_password2">Password confirmation:</label>
            <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
            <span class="helptext">Enter the same password as before, for verification.</span>
        </p>
        <ul class="errorlist">
            <li>This field is required.</li>
        </ul>
        <p>
            <label for="id_first_name">First name:</label>
            <input type="text" name="first_name" maxlength="30" required id="id_first_name">
        </p>


        <div id="sub-form-container">

        </div>

        <input type="submit" value="Register">
    </form>
</div>

<script type="text/javascript">
    const custHtml = `
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_last_name">Last name:</label>
        <input type="text" name="last_name" maxlength="30" required id="id_last_name">
    </p>
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_address">Address:</label>
        <input type="text" name="address" maxlength="60" required id="id_address">
    </p>`;


    const chefHtml = `
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_salary">Salary:</label>
        <input type="number" name="salary" min="-9223372036854775808" max="9223372036854775807" required id="id_salary">
    </p>
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_rating">Rating:</label>
        <input type="number" name="rating" required id="id_rating">
    </p>`;

    const deliveryHtml = `
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_salary">Salary:</label>
        <input type="number" name="salary" min="-9223372036854775808" max="9223372036854775807" required id="id_salary">  
    </p>`;

    const managerHtml = `
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_last_name">Last name:</label>
        <input type="text" name="last_name" maxlength="30" required id="id_last_name">
    </p>
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_salary">Salary:</label>
        <input type="number" name="salary" min="-9223372036854775808" max="9223372036854775807" required id="id_salary"> 
    </p>`;

    const salesHtml = `
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_last_name">Last name:</label>
        <input type="text" name="last_name" maxlength="30" required id="id_last_name">
    </p>
    <ul class="errorlist"><li>This field is required.</li></ul>
    <p>
        <label for="id_salary">Salary:</label>
        <input type="number" name="salary" min="-9223372036854775808" max="9223372036854775807" required id="id_salary">
    </p>`;

    function changeFormType(user_type) {
        let innerFormContainer = document.getElementById("sub-form-container")

        switch (user_type) {
            case "customer": 
                innerFormContainer.innerHTML = custHtml;
                break;
            case "chef": 
                innerFormContainer.innerHTML = chefHtml;
                break;
            case "delivery":
                innerFormContainer.innerHTML = deliveryHtml;
                break;
            case "sales":
                innerFormContainer.innerHTML = salesHtml;
                break;
            case "manager":
                innerFormContainer.innerHTML = managerHtml;
                break;
        }
    }

    document.getElementById("user_type_select").addEventListener("change", function () {
        changeFormType(this.value);
    })

    changeFormType("customer");
</script>
{% endblock %}

reg_log/templates/sales_register.html
<div class="sub-form-container">
    <form action="{% url 'sales_register' %}" method="POST" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
</div>